# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCIy87Cn8HdGK1_pDCLPmHYRJThoTlRX
"""

import torch
from torch import nn

import matplotlib.pyplot as plt

######################################
# Q1 Custom Dataset for 1D Function
######################################
class SimpleCurveData(torch.utils.data.Dataset):

  def __init__(self):
    self.x_data = torch.arange(-2.5,2.5,0.001).unsqueeze(1)
    self.y_data = 

  def __len__(self):
    return self.x_data.shape[0]

  def __getitem__(self, i):
    #TODO

######################################
# Q2 Feed Forward Neural Network
######################################

class FeedForwardNetwork(nn.Module):

  def __init__(self, input_dim, layer_widths, output_dim, activation=nn.ReLU):
    super().__init__()
    self.layer_widths = layer_widths
    assert(len(layer_widths) >= 1)

    #TODO


  def forward(self, x):
    #TODO
    pass
    return out

  def getParamCount(self):
    return sum(p.numel() for p in self.parameters())

######################################
# Q3 Training Loop
######################################

def train(model, dataloader):
  # TODO
  pass

def plotPredictions(model, dataloader, epoch, save_fig=False):
  dataset = dataloader.dataset
  # Switch to eval mode
  model.eval()

  # Make predictions for the full dataset
  y_pred = model(dataset.x_data)

  # Compute loss for reporting
  loss = ((dataset.y_data-y_pred)**2).mean().item()

  # Plot dataset and predictions
  plt.figure(figsize=(10,4))
  plt.plot(dataset.x_data.data, dataset.y_data.data, color="black", linestyle='dashed', label="True Function")
  plt.plot(dataset.x_data.data, y_pred.data, color="red", label="Network")
  plt.text(-2.6,-2.3, "Epoch: {}".format(epoch))
  plt.text(-2.6,-3.0, "Loss: {:0.3f}".format(loss))
  plt.text(-2.6,-3.7, "Params: {}  {}".format(model.getParamCount(), str(model.layer_widths)))
  plt.ylim(-4,10)

  if save_fig:
    plt.savefig("epoch{}.png".format(epoch))
  else:
    plt.show()

  model.train()


if __name__ == "__main__":
    # Generate a dataset for our curve
    dataset = SimpleCurveData()

    # Set up a dataloader to grab batches
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=64, shuffle=True)


    # Sanity Check: Visualize the whole dataset as a curve and a batch as points
    x_batch, y_batch = next(iter(dataloader))

    plt.figure(figsize=(10,4))
    plt.plot(dataset.x_data.data, dataset.y_data.data, color="black", linestyle='dashed', label="True Function")
    plt.scatter(x_batch, y_batch, c="red", s=40, label="Batch Samples",alpha=0.75, edgecolors='none')
    plt.legend()
    plt.title("Sanity Check: Curve Dataset and Dataloader")
    plt.show()


    ######################################
    # Q4 through Q7 Experimentation
    ######################################

    # Build our network
    layer_widths = [64]
    model = FeedForwardNetwork(1, layer_widths, 1, activation=nn.ReLU)

    train(model, dataloader)